# Generated by Django 3.1.7 on 2021-03-13 06:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210310_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='addfurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcategory', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('fdetail', models.CharField(max_length=50)),
                ('fprice', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('scontact', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone number'),
        ),
    ]
