# Generated by Django 3.1.7 on 2021-03-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210313_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfurniture',
            name='fcategory',
        ),
    ]
